# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 20:39
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0003_auto_20160820_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='projects',
            field=wagtail.wagtailcore.fields.StreamField((('project', wagtail.wagtailcore.blocks.StructBlock((('project_title', wagtail.wagtailcore.blocks.CharBlock(null=True, required=False)), ('project_description', wagtail.wagtailcore.blocks.CharBlock(null=True, required=False))), classname='project', icon='cogs')),), default=''),
            preserve_default=False,
        ),
    ]
