# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtaildocs', '0007_merge'),
        ('ctdata', '0004_homepage_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageProjectItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_external', models.URLField(blank=True, verbose_name='External link')),
                ('project_title', models.CharField(blank=True, max_length=255)),
                ('project_category', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], max_length=255)),
                ('project_link', models.URLField(verbose_name='Project Link')),
                ('project_description', models.CharField(blank=True, max_length=750)),
                ('featured', models.BooleanField()),
                ('link_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='projects',
        ),
        migrations.AddField(
            model_name='homepageprojectitem',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_items', to='ctdata.HomePage'),
        ),
    ]
