# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-22 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0005_auto_20160822_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageprojectitem',
            name='project_category',
            field=models.CharField(choices=[('story', 'Story'), ('portal', 'Portal')], max_length=255),
        ),
    ]
