# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 12:16
from __future__ import unicode_literals

from django.db import migrations
import fontawesome.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0007_servicespage_servicespagerelatedlink_servicespageresourceitem_socialmediasettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicespageresourceitem',
            name='icon',
            field=fontawesome.fields.IconField(blank=True, max_length=60),
        ),
    ]
