# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0009_jobpage_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpage',
            name='overview',
            field=models.CharField(default='', max_length=750),
            preserve_default=False,
        ),
    ]
