# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-25 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0010_jobpage_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='youtube',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(default='https://github.com/CT-Data-Collaborative/', help_text='Your GitHub URL'),
            preserve_default=False,
        ),
    ]
