# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-08 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0016_standardstreamfieldpage_standardstreamfieldpagecarouselitem_standardstreamfieldpagerelatedlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='audience',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='cost',
        ),
    ]
