# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-15 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0017_auto_20160908_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='blogpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='eventindexpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='eventpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='homepagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='jobindexpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='personpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='servicespagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='standardindexpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='standardpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
        migrations.AddField(
            model_name='standardstreamfieldpagerelatedlink',
            name='description',
            field=models.CharField(blank=True, help_text='Description', max_length=500),
        ),
    ]
