# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0021_auto_20161101_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferencesession',
            name='conference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='ctdata.ConferencePage'),
        ),
    ]
