# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0013_make_rendition_upload_callable'),
        ('ctdata', '0024_conferencesponsorlink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesponsorlink',
            name='description',
        ),
        migrations.AddField(
            model_name='conferencesponsorlink',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
