# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-03 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0025_auto_20161101_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conferencesession',
            name='session_title',
        ),
    ]
