# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0031_dataacademyabstractevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAcademyLiveEvent',
            fields=[
                ('dataacademyabstractevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyAbstractEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyabstractevent',),
        ),
        migrations.CreateModel(
            name='DataAcademyWebEvent',
            fields=[
                ('dataacademyabstractevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyAbstractEvent')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyabstractevent',),
        ),
    ]
