# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 16:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0032_dataacademyliveevent_dataacademywebevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='date_from',
            field=models.DateField(default=datetime.date(2016, 11, 22), verbose_name='Start date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='date_to',
            field=models.DateField(blank=True, help_text='Not required if event is on a single day', null=True, verbose_name='End date'),
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='signup_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='time_from',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='dataacademyliveevent',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dataacademyliveevent',
            name='size_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataacademywebevent',
            name='event_link',
            field=models.URLField(blank=True),
        ),
    ]
