# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('ctdata', '0033_auto_20161122_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyEventTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='ctdata.DataAcademyAbstractEvent')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctdata_academyeventtag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='dataacademyevent',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='dataacademywebevent',
            name='event_link',
            field=models.URLField(blank=True, help_text='Link to web conference page or archived webcast.'),
        ),
        migrations.DeleteModel(
            name='DataAcademyEvent',
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ctdata.AcademyEventTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
