# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('ctdata', '0035_academyeventrelatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='academyeventrelatedlink',
            name='related_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
