# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0036_academyeventrelatedlink_related_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileResource',
            fields=[
                ('dataacademyresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyresource',),
        ),
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('dataacademyresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyresource',),
        ),
        migrations.CreateModel(
            name='TopicGuideResource',
            fields=[
                ('dataacademyresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyresource',),
        ),
        migrations.CreateModel(
            name='TutorialResource',
            fields=[
                ('dataacademyresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ctdata.DataAcademyResource')),
            ],
            options={
                'abstract': False,
            },
            bases=('ctdata.dataacademyresource',),
        ),
        migrations.AddField(
            model_name='dataacademyabstractevent',
            name='create_eventbrite',
            field=models.BooleanField(default=False),
        ),
    ]
