# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-29 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0040_auto_20161129_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataAcademyTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Academy Tags',
                'verbose_name': 'Academy Tag',
            },
        ),
        migrations.AlterField(
            model_name='academyeventtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctdata_academyeventtag_items', to='ctdata.DataAcademyTag'),
        ),
        migrations.AlterField(
            model_name='academyresourcetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ctdata_academyresourcetag_items', to='ctdata.DataAcademyTag'),
        ),
        migrations.AlterField(
            model_name='dataacademyabstractevent',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ctdata.AcademyEventTag', to='ctdata.DataAcademyTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='dataacademyresource',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='ctdata.AcademyResourceTag', to='ctdata.DataAcademyTag', verbose_name='Tags'),
        ),
    ]
