# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-29 18:16
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0041_auto_20161129_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataacademytag',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
