# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0029_unicode_slugfield_dj19'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('ctdata', '0043_auto_20161129_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataacademycollection',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='DataAcademyCollection',
        ),
    ]
