# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-02 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0047_auto_20161201_1418'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopicGuideResource',
            new_name='LinkResource',
        ),
    ]
