# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0049_academyresourcerelatedlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='video_url',
            field=models.URLField(blank=True, verbose_name='Video URL'),
        ),
    ]
