# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-07 16:14
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0051_auto_20161206_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataacademypage',
            name='category_list_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataacademypage',
            name='explore_resources_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='dataacademypage',
            name='showcase_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
