# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-01-04 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0053_homepageprojectitem_project_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataacademyabstractevent',
            name='create_eventbrite',
        ),
        migrations.RemoveField(
            model_name='dataacademyabstractevent',
            name='eventbrite_event_id',
        ),
        migrations.RemoveField(
            model_name='dataacademyabstractevent',
            name='publish_eventbrite',
        ),
        migrations.RemoveField(
            model_name='dataacademyabstractevent',
            name='size_limit',
        ),
    ]
