# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0057_conferencesessionrelatedresources'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataacademypage',
            name='resource_index_page_title',
            field=models.CharField(default='Event Resources', max_length=20),
            preserve_default=False,
        ),
    ]
