# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0057_conferencesessionrelatedresources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='academy_resources_list_display',
            field=models.BooleanField(default=False, verbose_name='Resource List Display'),
        ),
    ]
