# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 17:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0058_dataacademypage_resource_index_page_title'),
        ('ctdata', '0058_auto_20170403_1448'),
    ]

    operations = [
    ]
