# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-17 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0060_scrollystory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrollystory',
            name='polling_interval',
            field=models.IntegerField(default=15, help_text='Enter how long (in minutes) the google sheets content should be cached for.'),
            preserve_default=False,
        ),
    ]
