# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 14:01
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0062_auto_20170417_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataacademypage',
            name='resource_index_text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
    ]
