# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-01 23:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctdata', '0070_auto_20170629_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dom_node', models.CharField(max_length=255)),
                ('css_url', models.URLField(blank=True, null=True)),
                ('jsbundle_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='blogpage',
            name='react_widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ctdata.ReactWidget'),
        ),
    ]
